app/models.py
from app import db
from datetime import datetime
class catinfo(db.Model):

	id = db.Column(db.Integer, primary_key=True)
	catname = db.Column(db.String(100), index=True)
	birthday = db.Column(db.DATE, index=True)
	sex = db.Column(db.String(200))
	headimage = db.Column(db.String(100),index=True)
	status = db.Column(db.Integer,index=True)
	timeinfos = db.relationship("timeinfo",backref = 'cat',lazy = 'dynamic')

	def __repr__(self):
		return '<catinfo {}>'.format(self.catname)
class timeinfo(db.Model):
	id = db.Column(db.Integer,primary_key=True)
	description = db.Column(db.String(100),index=True)#描述
	recordtime =db.Column(db.DATE)#记录时间
	type=db.Column(db.Integer)#1生日，2疫苗时间
	cat_id = db.Column(db.Integer,db.ForeignKey('catinfo.id'))
	def __repr__(self):
		return '<timeinfo {}>'.format(self.description)

app/main/forms.py
from flask_wtf import FlaskForm
from  wtforms import StringField,SubmitField,SelectField,DateField,FileField
from wtforms.validators import ValidationError,DataRequired
from flask_wtf.file import  FileAllowed, FileRequired,FileField
from app.models import catinfo

class addCatForm(FlaskForm):
	catname = StringField("名字",validators=[DataRequired()])
	birthday =DateField('生日',validators=[DataRequired()])
	sex = SelectField('性别',choices=[('公','公'), ('母', '母')])
	headimage =FileField('image',validators=[
        FileRequired(),
        FileAllowed(['jpg', 'png'], 'Images only!')
    ])
	submit = SubmitField('保存')

class addtimeForm(FlaskForm):
	time = DateField("记录时间",validators=[DataRequired()])
	description = StringField("描述",validators=[DataRequired()])
	type = SelectField('记录类型',choices=[('0','三联疫苗注射'),("1","狂犬疫苗注射"),("2","体内驱虫"),
									   ("3","体外驱虫")])
	submit = SubmitField("保存")

app/__init__.py
# -*- coding:utf-8 -*-
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config
from  flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from flask_moment import Moment
from flask_uploads import UploadSet, configure_uploads,IMAGES
db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()
moment = Moment()#本地化时间
photos = UploadSet('PHOTO')

def create_app(config_class=config):
	app = Flask(__name__)
	app.config.from_object(config_class)
	db.init_app(app)
	migrate.init_app(app,db)
	bootstrap.init_app(app)
	configure_uploads(app, photos)
	moment.init_app(app)
	from app.main import bp as main_bp
	app.register_blueprint(main_bp)
	return app

from app import models

app/main/__init__.py
from flask import Blueprint
bp = Blueprint('main', __name__)
from app.main import routes

app/main/routes.py
# -*- coding:utf-8 -*-
from flask import render_template,flash,redirect,url_for,request,g,jsonify,current_app
from  app import db,photos,create_app
from app.main import bp
from app.models import catinfo,timeinfo
from app.main.forms import addCatForm,addtimeForm
from config import config
import os
import requests
from flask_uploads import UploadSet,IMAGES,configure_uploads


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
def index():
	cat = catinfo.query.all()
	return render_template('index.html',cats=cat)

@bp.route('/addCat',methods = ['GET', 'POST'])
def addCat():
	'''添加一只猫'''
	form = addCatForm()
	if form.validate_on_submit():#验证表单数据
		headimage = form.headimage.data
		a = photos.save(headimage)
		cat = catinfo(catname=form.catname.data,birthday=form.birthday.data
					  ,sex = form.sex.data,headimage = photos.url(a),status=1)
		db.session.add(cat)
		db.session.commit()
		flash('保存成功')
		return  redirect(url_for('main.index'))
	return  render_template('addcat.html',form=form)

@bp.route('/alterCat/<id>',methods = ['GET', 'POST'])
def alterCat(id):
	cat = catinfo.query.filter_by(id=id).first()
	form = addCatForm()
	print(form.catname.data)
	print(form.birthday.data)
	print(form.sex.data)
	print(form.headimage.data)
	print(form.validate_on_submit())
	if form.validate_on_submit():#验证表单数据
		headimage = form.headimage.data
		a = photos.save(headimage,headimage.filename)
		cat.catname = form.catname.data
		cat.birthday = form.birthday.data
		cat.sex = form.sex.data
		cat.headimage=photos.url(a)

		db.session.commit()
		flash('修改成功')
		return  redirect(url_for('main.index'))
	return render_template("alterCat.html",cat=cat,form=form)
basedir = os.path.abspath(os.path.dirname(__file__))
def allowed_file(filename):
	return '.' in filename and \
		   filename.rsplit('.', 1)[1].lower() in config.ALLOWED_EXTENSIONS

@bp.route('/deleteCat/<id>',methods = ['GET'])
def deleteCat(id):
	cat = catinfo.query.filter_by(id=id).first()
	if cat :
		cat.status=0
		db.session.commit()
		flash("删除成功")
		return jsonify({'code':0,"message":'删除成功'})
	return jsonify({'code':-1,"message":'删除失败'})
@bp.route('/addtime/<id>',methods = ['GET', 'POST'])
def addtime(id):
	cat = catinfo.query.filter_by(id=id).first()

	form = addtimeForm()
	if form.validate_on_submit():
		time_info = timeinfo(description=form.description.data, recordtime=form.time.data, type=form.type.data, cat_id=id)
		db.session.add(time_info)
		db.session.commit()
		return redirect(url_for("main.index"))
	# print(cat.timeinfos.all())
	return render_template("abouttime.html",form=form,times = cat.timeinfos)

app/templates/_cat.html
<table class="table table-hover">

    <tr>
        <td>
            <img src="{{ cat.headimage }}" width="5%" height="5%">
            <br>
            <a style="color: black ">
                名字：{{ cat.catname }}
            </a>
        <br>
            <a>
                生日：{{ cat.birthday }}
            </a>
        <br>
            <a>
                性别：{{ cat.sex }}
            </a>
         <div class="btn-group" style="float:right">
              <button type="button" class="btn btn-info">更多</button>
              <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
             <ul class="dropdown-menu">
                <li><a href={{ url_for('main.alterCat',id=cat.id) }}>修改资料</a></li>
                <li><a href="javascript:a('{{ cat.id }}')"  >删除这只猫</a>
                <script>
                    function a(catid) {

                        if (confirm("确定删除吗？")) {

                        url = "/deleteCat/"+catid
            　　　　　　　　　$.get(url
                        ).done(function(response) {
                           rej=  JSON.stringify(response);

                            alert(response.message)
                        }).fail(function() {
                            alert("请稍后再试")

                        });
                    }


        }



    </script></li>
{#                 #url_for('main.deleteCat',id= cat.id) }}#}
                <li><a href={{ url_for("main.addtime",id = cat.id) }}>添加时间记录</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
              </ul>
        </div>
        </td>

    </tr>
</table>

app/templates/_timeinfo.html
<table class="table table-striped table-bordered table-hover table-condensed " border="5"  >
    <tr>
        <th style="text-align: center;">类型</th>
        <th style="text-align: center;height: 30px">日期</th>

        <th style="text-align: center;">描述</th>
    </tr>
    {% for timeinfo in times %}
        <tr>

            <td style="text-align: center;">
            {% if  timeinfo.type==0  %}
                三联疫苗注射
                {% elif  timeinfo.type==0%}
                狂犬疫苗注射
                {% else  %}
                体内驱虫
                {% endif %}
            </td>
            <td style="text-align: center;">{{ timeinfo.recordtime }}</td>
            <td style="text-align: center;">{{ timeinfo.description }}</td>

        </tr>
    {% endfor %}


</table>

app/templates/abouttime.html
{% extends 'base.html' %}
{% block title %}
    修改信息
{% endblock %}
{% block app_content %}
    {% include '_timeinfo.html' %}



        <h3>添加相关时间记录</h3>
       <form role="form" method="post" >
              {{ form.hidden_tag() }}
            <p>
                {{ form.time.label }}<br>
                {{ form.time(type = "date") }}


            </p>
            <p>
                {{ form.description.label }}<br>
                {{ form.description }}

            </p>
            <p>{{ form.type.label }}<br>
                {{ form.type }}


            <p>{{ form.submit() }}</p>


        </form>



{% endblock %}

app/templates/addcat.html
{% extends 'base.html' %}
{% block app_content %}
    <h1>添加猫信息</h1>
    <form role="form" method="post" enctype="multipart/form-data">
              {{ form.hidden_tag() }}
            <p>
                {{ form.catname.label }}<br>
                {{ form.catname }}


            </p>
            <p>
                {{ form.birthday.label }}<br>
                {{ form.birthday(type = "date") }}

            </p>
            <p>{{ form.sex.label }}<br>
                {{ form.sex }}

            <p>
                {{form.headimage.label}}<br>
                {{form.headimage}}<br>
            </p>
            <p>{{ form.submit() }}</p>


        </form>
{% endblock %}

app/templates/alterCat.html
{% extends 'base.html' %}
{#{% import 'bootstrap/wtf.html' as wtf %}#}
{% block title %}
    修改信息
{% endblock %}
{% block app_content %}

        <div style="width:300px; margin:0 auto;">
        <h1>修改{{ cat.catname }}信息</h1>
        <form role="form" method="POST" enctype="multipart/form-data">
              {{ form.hidden_tag() }}
            <p>
                {{ form.catname.label }}<br>
                {{ form.catname(value=cat.catname) }}
                {% for error in form.catname.errors %}
            <span style="color:red;">{{ error }}</span>
        {% endfor %}
            </p>
            <p>
                {{ form.birthday.label }}<br>
                {{ form.birthday(type="date",value=cat.birthday) }}
                {% for error in form.birthday.errors %}
            <span style="color:red;">{{ error }}</span>
        {% endfor %}
            </p>
            <p>{{ form.sex.label }}<br>
                {{ form.sex (value=cat.sex)}}
        {% for error in form.sex.errors %}
            <span style="color:red;">{{ error }}</span>
        {% endfor %}
            <p>
                {{form.headimage.label}}<br>
                {{form.headimage(value=cat.headimage)}}
            {% for error in form.headimage.errors %}
            <span style="color:red;">{{ error }}</span>
        {% endfor %}
            </p>
            <p>{{ form.submit }}</p>


        </form>
        </div>




{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.lang(g.locale) }}
    <script>
        function translate(sourceElem, destElem, sourceLang, destLang) {
            $(destElem).html('<img src="">');
            $.post('/translate', {
                text: $(sourceElem).text(),
                source_language: sourceLang,
                dest_language: destLang
            }).done(function(response) {
                $(destElem).text(response['text'])
            }).fail(function() {
                $(destElem).text("Error: Could not contact server.");
            });
        }
        var photoUpload = upload.render({
            elem: '#btn_photo'
            , url: '/flask-upload'
            , exts: 'jpg|png|jpeg'
            , size: 5120
            , before: function (obj) {
                obj.preview(function (index, file, result) {
                    $('#photo').attr('src', result);
                    $('#photo').css('width', '300');
                    $('#photo').css('height', '300');
                });
            }
            , done: function (res) {
                if (res.code == 0) {
                    layer.msg(res.filename + '上传成功！');
                    var href = '<a href="' + res.msg + '" style="color:blue; text-decoration: solid;">' + res.msg + '</a>'
                    $('#txt_photo').html(href)
                } else {
                    return layer.msg('上传失败');
                }
            }
            , error: function () {
                var photo = $('#txt_photo');
                photo.html('<span style="color: #FF5722;">上传失败</span> <a class="layui-btn layui-btn-mini demo-reload">重试</a>');
                photo.find('#btn_photo').on('click', function () {
                    photoUpload.upload();
                });
            }
        });
    </script>

{% endblock %}

 {% block title %}
    CAT
{% endblock %}
 {% block navbar %}
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">CAT</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href={{ url_for('main.index') }}>Home</a></li>
                    <li><a href={{ url_for('main.addCat') }}>添加</a></li>
                </ul>
                {% if g.search_form %}
                <form class="navbar-form navbar-left" method="get"
                        action="">
                    <div class="form-group">
                        {{ g.search_form.q(size=20, class='form-control',
                            placeholder=g.search_form.q.label.text) }}
                    </div>
                </form>
                {% endif %}
                <ul class="nav navbar-nav navbar-right">

                    <li><a href=""> 'Login' </a></li>

                    <li><a href="">'profile'</a></li>
                    <li><a href="">Logout</a></li>

                </ul>
            </div>
        </div>




 </nav>
{% endblock %}
 {% block content %}
    <div class="container">
         {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
         {% endfor %}
        {% endif %}
        {% endwith %}{# application content needs to be provided in the app_content block #}

        {% block app_content %}
        {% endblock %}
    </div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block app_content %}
    {% for cat in cats %}
        {% if cat.status ==1 %}
            {% include '_cat.html' %}

        {% endif %}

    {% endfor %}



{% endblock %}